### ISSUE TITLE
jQuery 3.5

### ISSUE THREAD

**Issue by rolltidega** [splunk/splunk-add-on-microsoft-azure#10]
I saw 3.2.0 had some jquery updates but did that address jQuery 3.5?  The upgrade readiness app from Splunk still shows 4.0.2 as not compatible.

**Comment by JasonConger** [comment]
Do you have the details from the readiness app?  The current version of the add-on should be compatible with jQuery 3.5.  I've run the readiness app on this add-on and didn't see jQuery issues, but I'm interested in what your readiness app is displaying so that we can get these things addressed.
