### ISSUE TITLE
Entry.js error

### ISSUE THREAD

**Issue by norbertt911** [splunk/splunk-add-on-microsoft-azure#17]
Hi,

With the 4.0.2 version of the app I experienced the following error on Splunk Enterprise 9.0.0 and on 8.2.5: 
![TA-MS-AAD](https://user-images.githubusercontent.com/54628405/187641358-eb6d76e8-3d59-452c-b848-f597d870f178.JPG)

(Rolling back to 3.2 solves the issue for now...)

**Comment by JasonConger** [comment]
What OS is in use?

**Comment by norbertt911** [comment]
CentOs 7

I played with it recently on a test server and seems the clean install of the app does not reproduce this error. 
But I  keep "lost" the input tab like 2 times from 5. I did the change for pwd import in entry.js but seems it does not help 100%. Splunk restart helps (or sometimes not :) )

**Comment by JasonConger** [comment]
Addressed in 4.0.3
