### ISSUE TITLE
azure_vuln eventtype search is broken

### ISSUE THREAD

**Issue by ashurack** [splunk/splunk-add-on-microsoft-azure#19]
Typo in the `azure_vuln` stanza.  Should be brought into one line.

```
Invalid key in stanza [azure_vuln] in /opt/splunk/etc/apps/TA-MS-AAD/default/eventtypes.conf, line 40: properties.additionalData.cve{}.title (value: *)).
```

https://github.com/splunk/splunk-add-on-microsoft-azure/blob/4.0.2/package/default/eventtypes.conf#L38-L40

**Comment by JasonConger** [comment]
Addressed in 4.0.3
