### ISSUE TITLE
Ignoring index_stats flag

### ISSUE THREAD

**Issue by EricMooreHays** [splunk/splunk-add-on-microsoft-azure#25]
I find that the app ignores the directive index_stats=0 

the app sets the flag to 0 or 1, and at line 120 in azure_kql.py if tests this as 
```
if (index_stats):
    headers = {
       "Prefer": "include-statistics=true"
     }
```

this fires regardless of the status of the directive. 

the following is crude but works: 
```
                if index_stats=="1" or index_stats.upper()=="TRUE": 
                    headers = {
                        "Prefer": "include-statistics=true"
                    }
```

**Comment by JasonConger** [comment]
KQL inputs have moved to the [Splunk Add-on for Microsoft Cloud Services](https://splunkbase.splunk.com/app/3110)
