### ISSUE TITLE
Problem creating new AAD Audit Input

### ISSUE THREAD

**Issue by SgtMoose** [splunk/splunk-add-on-microsoft-azure#3]
We just upgraded the TA to the latest version released to Splunk Cloud due to problems pulling data for Audit and Signin Inputs.

When we go to create a new AAD Audit input we receive the following error when saving the Input.

b'{"messages":[{"type":"ERROR","text":"The following required arguments are missing: AAD_sign_in_note."}]}'

![Inputs - Google Chrome 2022-07-13 09 58 04](https://user-images.githubusercontent.com/7230916/178752271-ac7024d3-16c5-4fe6-8390-38be33dd144d.png)

**Comment by JasonConger** [comment]
A fix has been committed to the repo.  As an immediate workaround, you can create the input by creating/modifying `local/inputs.conf`

https://github.com/splunk/splunk-add-on-microsoft-azure/wiki/Configure-Azure-Active-Directory-Audit-inputs-for-the-Splunk-Add-on-for-Microsoft-Azure#configure-inputs-using-configuration-files

**Comment by SgtMoose** [comment]
Appreciate the quick response Jason but we are a Splunk Cloud customer and will wait to see the updated TA with the fix made available to Splunk Cloud since we do not have direct backend access to create inputs.  

Do you know how long it will take for the fixed version to make it to Splunk Cloud?

**Comment by JasonConger** [comment]
Version 4.0.2 is available on Splunkbase and Splunk Cloud
