### ISSUE TITLE
Migration to MSAL?

### ISSUE THREAD

**Issue by lc9er** [splunk/splunk-add-on-microsoft-azure#30]
Microsoft reports they are ending support for ADAL in December (No - for realsies this time), in favor of MSAL. ADAL should still work for an unspecified amount of time. Are there any plans to migrate to MSAL? The add-on shows up in my logs as using ADAL still. Thanks.

More info: https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-get-list-of-all-active-directory-auth-library-apps

**Comment by JasonConger** [comment]
This add-on does not use ADAL.  Are you reusing the Azure AD app registration elsewhere?
