### ISSUE TITLE
Failed Python Scan in Upgrade Readiness App

### ISSUE THREAD

**Issue by jacobc8701** [splunk/splunk-add-on-microsoft-azure#33]
Hello, 

I am using the upgrade readiness app (v4.0.2) and running the python scan for v4.0.3 of this app. I am getting "This app is not compatible with Python 3"

Can you please confirm if this is true or not? And what might be causing it? perhaps some older SDK is being detected?

Thanks,
Chris

**Comment by JasonConger** [comment]
I cannot reproduce this with version 4.0.2 of the upgrade readiness app and version 4.0.3 of the Azure add-on.  I'm showing a pass on the Azure add-on.  Can you export your results for the Azure add-on and paste them here or send the result to jconger [at] splunk.com?
