### ISSUE TITLE
Intermittently failing inputs for Azure:metrics and Azure:Compute* Sourcetypes

### ISSUE THREAD

**Issue by SummerTwentytwo** [splunk/splunk-add-on-microsoft-azure#36]
Hi,

I am new to this platform. 

We are constantly observing the inputs  Azure:metrics and Azure:Compute* failing to ingest since 22/11/2022. As a workaround we disabled the input and reenable it and events starts ingesting. Is there a permanent solutions for this? 

Current Microsoft Azure Add-on for Splunk version 3.2.0. Splunk cloud version:9.0.2208.4

Hoping to get some insight.

**Comment by JasonConger** [comment]
I would suggest upgrading to version 4.x of the add-on.  Some improvements were made to the underlying Python to use `Session()` and `Retry()` classes.  This aids in REST throttling and automatic retries.
