### ISSUE TITLE
riskUsers permissions

### ISSUE THREAD

**Issue by McCurity** [splunk/splunk-add-on-microsoft-azure#43]
I'm not certain why but on February 5th it appears I started getting errors for:

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/identityProtection/riskyUsers

In looking at the Graph API Explorer permissions it seems that endpoint requires IdentityRiskyUser.Read.All however that permission is not identified on the permissions spreadsheet
https://docs.google.com/spreadsheets/d/1YJAqNmcXZU-7O9CxVKupOkR6q2S8TXriMeLAUMYmMs4/edit#gid=0

I suspect it's the permissions spreadsheet that needs updated but for it to start happening a month ago with no app updates since Sept I can only conclude MS modified something on their side.

**Comment by JasonConger** [comment]
The permission sheet has been updated.
