### ISSUE TITLE
Addon dropping events more than 50%

### ISSUE THREAD

**Issue by Urus341** [splunk/splunk-add-on-microsoft-azure#46]
Hello Guys,  Observed that Addon is dropping events more than 50% in Log Analytics KQL. Is there any limitation that was configured in any script ?

The KQL query was running fine on Log analytics and giving the results but only few logs gets ingested into Splunk

Example: 10000 logs returned on Log analytics with KQL query. Only 5500 logs ingested into Splunk with same query configured on Add-on.

Would anyone please help here ?

**Comment by JasonConger** [comment]
KQL inputs have moved to the [Splunk Add-on for Microsoft Cloud Services](https://splunkbase.splunk.com/app/3110).
