### ISSUE TITLE
Issue in pulling Azure platform audit logs in Splunk

### ISSUE THREAD

**Issue by vnt-mmorsiani** [splunk/splunk-add-on-microsoft-azure#51]
Hello everyone,
Vontier InfoSec team needs your help in fixing an issue we’re currently facing when trying to pull Azure audit logs in Splunk.
The integration to pull this specific data is configured on Splunk side through the Splunk Add-on for Microsoft Azure (Version 4.0.3, Build 1663711863) and looking at the integration logs on Splunk side, I have found a specific error (see attachments).
This integration is not new. It did work well for months. Then suddenly it broke.

![splunk-integration-error](https://github.com/splunk/splunk-add-on-microsoft-azure/assets/135701506/7a630998-afe9-4887-9d7a-20995b48f121)

VNT InfoSec and VNT Cloud teams did dig deeper and we think we have found the root cause of this issue.
Looking at the logs, the Graph API call we saw is the following.

https://graph.microsoft.com/v1.0/auditLogs/directoryAudits?$orderby=activityDateTime&$filter=activityDateTime+gt+2022-06-07T06:44:54.23518Z+and+activityDateTime+le+2023-05-26T13:19:07.832439Z 

Now in the input config dialog box if no value is given in the “Start Date” field the input will start getting data 7 days in the past. 
But looking again at the start date in the query above you can see that the start date is in the 2022!

![graph-query-wrong-startdate](https://github.com/splunk/splunk-add-on-microsoft-azure/assets/135701506/511429b6-aabd-4a18-9393-09426f80e4d8)

Then we tried to query the Azure platform using the MS Graph explorer tool and we used the same query but with a proper start date. See below the query used in Graph Explorer.

https://graph.microsoft.com/v1.0/auditLogs/directoryAudits?$orderby=activityDateTime&$filter=activityDateTime+gt+2023-04-25T06:44:54.23518Z+and+activityDateTime+le+2023-05-26T13:19:07.832439Z

![graph-query-good-startdate](https://github.com/splunk/splunk-add-on-microsoft-azure/assets/135701506/81593bee-1258-4b63-879e-a110ec16f15b)

Using this tweaked query, we obtain audit data from Azure (see attached picture).

![graph-query-with-results](https://github.com/splunk/splunk-add-on-microsoft-azure/assets/135701506/09d1e5b8-0420-4247-b45d-312838572e69)

So the root cause is the Start Date value that is wrong compared to the settings in the input config field (see attached picture).

![azure-audit-input-settings](https://github.com/splunk/splunk-add-on-microsoft-azure/assets/135701506/3659896c-bdcd-417d-bc99-ed95f351c621)

Furthermore, we tried to enter the good Start Date we used in Graph Explorer, but the dialog box didn’t accept the setting despite is correct (see attached picture). 
Maybe another bug?

All the findings have been shared with Splunk support. They suggested to submit an issue to the developer.

We need your help to review/fix this issue to restart pulling this data into Splunk.

Please let me know if you have any comments, questions, or concerns.

Thanks.

Regards.
Massimo Morsiani - VNT Information Security

**Comment by vnt-mmorsiani** [comment]
Sorry I forgot to attach the error in the dialog box I mentioned.

![azure-audit-input-error](https://github.com/splunk/splunk-add-on-microsoft-azure/assets/135701506/1bfdf33b-4c46-4d5d-a1bc-13051734c914)

**Comment by vnt-mmorsiani** [comment]
Hello everyone,
any feedback about this issue?
Thanks.

Regards.
Massimo Morsiani - VNT Information Security

**Comment by JasonConger** [comment]
This looks like an old checkpoint value was picked up.  The checkpoint holds the last date/time read as the starting point for the next query.  Checkpoints key off of the input name.  So, if a new input was created that reused an old input name, an old start date could be picked up.

Checkpoint values can be observed by navigating to Troubleshooting > View Checkpoints within the add-on.

Setting a start date in the input will not override the checkpoint start date.  Here is a link to the specific logic => https://github.com/splunk/splunk-add-on-microsoft-azure/blob/8330f66d155af431fb4e704239d8f12517b68785/package/bin/MS_AAD_audit.py#L40

Creating a new input with a new name should correct the issue.
