### ISSUE TITLE
Authentication protocol field in SignIn logs

### ISSUE THREAD

**Issue by cdc-eba** [splunk/splunk-add-on-microsoft-azure#56]
Hello, 

I am not able to find the Authentication Protocol field in the SignIn logs, I am wondering if it is actually possible to retreive it as I can see the option to filter in the Azure Portal / SignIn view.

If it is possible, this information could be valuable, especially to detect the Device Code attack that has been described here: https://aadinternals.com/post/phishing/.

Best,

**Comment by cdc-eba** [comment]
This needs to use the beta version of the API on this file: https://github.com/splunk/splunk-add-on-microsoft-azure/blob/main/package/default/inputs.conf#L2

Is this planned to use the beta version sometime in the future?

**Comment by JasonConger** [comment]
You can specify the endpoint (`v1.0` or `Beta`) when creating an input. 
<img width="784" alt="image" src="https://github.com/splunk/splunk-add-on-microsoft-azure/assets/1494469/0eb163a8-429c-4a11-9467-e846d758bfe6">

**Comment by cdc-eba** [comment]
Great thanks!!
