### ISSUE TITLE
Unable to obtain access token

### ISSUE THREAD

**Issue by sohjc1988** [splunk/splunk-add-on-microsoft-azure#58]
Splunk was unable to pull logs from Azure after the secret expired. After replacing the secret value, we are met with the error Unable to obtain access token in the audit logs.

1) Why do we have this error?
2) Do we need to resetup the whole azure app + inputs when the secret expires?

**Comment by JasonConger** [comment]
Updating the secret via the User Interface will update the secret the code uses to connect to Azure endpoints.
