### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED: Self signed certificate in certificate chain _ssl.c.1106

### ISSUE THREAD

**Issue by anantadeshpande** [splunk/splunk-add-on-microsoft-azure#67]
Hi Team,
We have installed splunk/splunk-add-on-microsoft-azure latest version 4.0.3 on Splunk HF. We are getting below certificate error. We use company provided internal ROOT CA certificates. We faced similar issue with MS Cloud Services Add-on but resolved when appended our root certificates under $SPLUNK_HOME/etc/apps/<TA_NAME>/lib/certifi/cacert.pem. But not working this time. Splunk version is 9.0.6

Looks like this TA looks other path for ssl certificate. Could you please share the exact path were we should append our internal certificates.

Error as below:
- message from "$SPLUNK_HOME/etc/apps/TA-MS-AAD/bin/MS_AAD_signins.py"  HTTPSConnectionPool(host='login.microsoftonline.com', port=443) Max retries exceed with url:/<tenant_id>/oauth2/v2.0/token (caused by sslerror(SSL: CERTIFICATE_VERIFY_FAILED: Self signed certificate in certificate chain _ssl.c.1106))

**Comment by JasonConger** [comment]
In `$SPLUNK_HOME/etc/apps/TA-MS-AAD/lib/certifi` add your root certificate to `cacert.pem`
