### ISSUE TITLE
Missing normalised fields (userDisplayName) in CIM

### ISSUE THREAD

**Issue by ajoergensson** [splunk/splunk-add-on-microsoft-azure#70]
This thread is meant to highlight the missing fields that should be normalised in the CIM

- userDisplayName

**Comment by ajoergensson** [comment]
`[ms:aad:signin]
## Field Aliases
# Non CIM Fields
FIELDALIAS-ms_aad_sign_in_signinDateTime = createdDateTime AS signinDateTime
# CIM Authentication
FIELDALIAS-ms_aad_sign_in_authentication_authentication_method = authenticationDetails{}.authenticationMethod as authentication_method
FIELDALIAS-ms_aad_sign_in_authentication_reason = status.failureReason as reason
FIELDALIAS-ms_aad_sign_in_authentication_src = ipAddress AS src
FIELDALIAS-ms_aad_sign_in_authentication_src_ip = ipAddress AS src_ip
FIELDALIAS-ms_aad_sign_in_authentication_user_agent = UserAgent as user_agent
## Calculated Fields
# CIM Common Fields
EVAL-vendor_product = "Microsoft Azure Active Directory"
# CIM Authentication
EVAL-action = if('status.errorCode'==0,"success","failure")
EVAL-app = lower(replace(appDisplayName, " ", ":"))
EVAL-dest = if(resourceDisplayName == "null","https://login.microsoftonline.com",lower(replace(resourceDisplayName, " ", ".")))
EVAL-duration = processingTimeInMilliseconds/1000
EVAL-user = lower(userPrincipalName)
EVAL-user_id = lower(userPrincipalName)
EVAL-userDisplayName = lower(userDisplayName)
KV_MODE = json
MAX_TIMESTAMP_LOOKAHEAD = 30
SHOULD_LINEMERGE = 0
TIME_PREFIX = \"createdDateTime"\:\s*\"
TRUNCATE = 0

[azure:aad:signin]
## Field Aliases
# Non CIM Fields
FIELDALIAS-azure_aad_sign_in_signinDateTime = createdDateTime AS signinDateTime
# CIM Authentication
FIELDALIAS-azure_aad_sign_in_authentication_authentication_method = authenticationDetails{}.authenticationMethod as authentication_method
FIELDALIAS-azure_aad_sign_in_authentication_reason = status.failureReason as reason
FIELDALIAS-azure_aad_sign_in_authentication_src = ipAddress AS src
FIELDALIAS-azure_aad_sign_in_authentication_src_ip = ipAddress AS src_ip
FIELDALIAS-azure_aad_sign_in_authentication_user_agent = UserAgent as user_agent
## Calculated Fields
# CIM Common Fields
EVAL-vendor_product = "Microsoft Azure Active Directory"
# CIM Authentication
EVAL-action = if('status.errorCode'==0,"success","failure")
EVAL-app = lower(replace(appDisplayName, " ", ":"))
EVAL-dest = if(resourceDisplayName == "null","https://login.microsoftonline.com",lower(replace(resourceDisplayName, " ", ".")))
EVAL-duration = processingTimeInMilliseconds/1000
EVAL-user = lower(userPrincipalName)
EVAL-user_id = lower(userPrincipalName)
EVAL-userDisplayName = lower(userDisplayName)
KV_MODE = json
MAX_TIMESTAMP_LOOKAHEAD = 30
SHOULD_LINEMERGE = 0
TIME_PREFIX = \"createdDateTime"\:\s*\"
TRUNCATE = 0`

**Comment by ajoergensson** [comment]
I am unable to generate a branch from the issue. Kindly grant us the necessary permissions to carry out this action :)

**Comment by ajoergensson** [comment]
Inside props.conf in the TA

`FIELDALIAS-azure_aad_sign_in_authentication_user_display_name = userDisplayName AS user_display_name
EVAL-user_display_name = lower(userDisplayName)`

**Comment by JasonConger** [comment]
Addressed in version 4.1.0
