### ISSUE TITLE
Management URI hard-coded in various places

### ISSUE THREAD

**Issue by beaunewcomb79** [splunk/splunk-add-on-microsoft-azure#72]
Troubleshooting an issue pulling a full set of VMs from a subscription that lives in GovCloud, and noticed a bunch of 404's in the debug logs...  manually updating lines 23 and 42 of utils.py to change uri to {management_base_url} made the 404's go away, but still not getting the entire list of VMs (despite getting them in full via the AZ CLI)

**Comment by JasonConger** [comment]
Are you selecting "Azure Government" as the environment when creating the input?  This will control when base URL to use => https://github.com/splunk/splunk-add-on-microsoft-azure/blob/8330f66d155af431fb4e704239d8f12517b68785/package/bin/ta_azure_utils/utils.py#L254

<img width="750" alt="image" src="https://github.com/splunk/splunk-add-on-microsoft-azure/assets/1494469/e83060c6-fe94-4c73-8021-b76eba283980">

**Comment by beaunewcomb79** [comment]
Yeah, I did.. after I updated the hardcoded management url's the 404's stopped showing in the debug logs, but the pull stops at 100 VMs exactly.  This tells me there's an equivalent to --first 100 (default) with the AZ CLI...  I just can't figure out how to work the equivalent into the python... looks like its setup to handle nextLink, but it doesn't appear it is

**Comment by JasonConger** [comment]
What URL did you have to hardcode?  The add-on should have selected the right endpoint depending on which environment you chose.

**Comment by beaunewcomb79** [comment]
I "UN-HARDCODED" a few places where the public management URI was in utils.py and azure_comp.py 

Line 22 in azure_comp.py is an example

After variablizing the URI, 404s went away for instanceView, but nextLink doesn't seem to be handled correctly because it just stops at 100 VMs, and there's no debug error logged as to why.

**Comment by JasonConger** [comment]
Addressed in version 4.1.0
