### ISSUE TITLE
Errormin web ui

### ISSUE THREAD

**Issue by saravanakumar-subbiah** [splunk/splunk-add-on-microsoft-azure#8]
I am getting error message. while i open AD

Unable to initialize modular input "azure_virtual_network" defined in the app "TA-MS-AAD": Introspecting scheme=azure_virtual_network: script running failed (exited with code 1).. 7/26/2022, 12:48:39 PM

Error: Request failed with status code 500 in webui, any help ?

**Comment by JasonConger** [comment]
Was this an in-place upgrade or a clean install?

**Comment by saravanakumar-subbiah** [comment]
Clean Install only. After downgrade to 3.1 it is working.

On 27-Jul-2022 4:16 am, Jason Conger ***@***.***> wrote:

Was this an in-place upgrade or a clean install?

**Comment by JasonConger** [comment]
What OS and Splunk version are you using?

**Comment by saravanakumar-subbiah** [comment]
Windows 2012 server
Splunk 9.0




Saravanakumar. S
Manager - Security Operations
Hand Phone:8754485958

**Comment by JasonConger** [comment]
The root cause has been identified as a Python module import.

Workaround:

1. Open the file `import_declare_test.py` located in `$SPLUNK_HOME/etc/apps/TA-MS-AAD/bin`
2. Comment out the `import pwd` line.  It should look like this:
```
import os
#import pwd
import sys
```

3. Restart Splunk

**Comment by saravanakumar-subbiah** [comment]
Still I am seeing this error .


Saravanakumar. S
Manager - Security Operations
Hand Phone:8754485958

**Comment by JasonConger** [comment]
Addressed in 4.0.3
